name: Validate CloudFormation Templates

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cfn-lint
        run: |
          pip install cfn-lint

      - name: Run cfn-lint
        run: |
          cfn-lint template.yml

