name: Validate CloudFormation Template

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate CloudFormation template
      run: |
        ls -al # List files to ensure template.yaml is present
        aws cloudformation validate-template --template-body file://template.yaml
