name: Validate CloudFormation Template

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug - List files in the working directory
      run: |
        echo "Listing files in the working directory:"
        ls -al

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        aws --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Debug - Check AWS configuration
      run: |
        aws sts get-caller-identity

    - name: Validate CloudFormation template
      run: |
        aws cloudformation validate-template --template-body template.yaml
